@startuml

title __VIDEO's Class Diagram__\n

  package org.opencv {
    package org.opencv.video {
      class BackgroundSubtractor {
          # BackgroundSubtractor()
          {static} + __fromPtr__()
          + apply()
          + apply()
          + getBackgroundImage()
          # finalize()
          {static} - apply_0()
          {static} - apply_1()
          {static} - getBackgroundImage_0()
          {static} - delete()
      }
    }
  }
  

  package org.opencv {
    package org.opencv.video {
      class BackgroundSubtractorKNN {
          # BackgroundSubtractorKNN()
          {static} + __fromPtr__()
          + getDetectShadows()
          + getDist2Threshold()
          + getShadowThreshold()
          + getHistory()
          + getNSamples()
          + getShadowValue()
          + getkNNSamples()
          + setDetectShadows()
          + setDist2Threshold()
          + setHistory()
          + setNSamples()
          + setShadowThreshold()
          + setShadowValue()
          + setkNNSamples()
          # finalize()
          {static} - getDetectShadows_0()
          {static} - getDist2Threshold_0()
          {static} - getShadowThreshold_0()
          {static} - getHistory_0()
          {static} - getNSamples_0()
          {static} - getShadowValue_0()
          {static} - getkNNSamples_0()
          {static} - setDetectShadows_0()
          {static} - setDist2Threshold_0()
          {static} - setHistory_0()
          {static} - setNSamples_0()
          {static} - setShadowThreshold_0()
          {static} - setShadowValue_0()
          {static} - setkNNSamples_0()
          {static} - delete()
      }
    }
  }
  

  package org.opencv {
    package org.opencv.video {
      class BackgroundSubtractorMOG2 {
          # BackgroundSubtractorMOG2()
          {static} + __fromPtr__()
          + getDetectShadows()
          + getBackgroundRatio()
          + getComplexityReductionThreshold()
          + getShadowThreshold()
          + getVarInit()
          + getVarMax()
          + getVarMin()
          + getVarThreshold()
          + getVarThresholdGen()
          + getHistory()
          + getNMixtures()
          + getShadowValue()
          + apply()
          + apply()
          + setBackgroundRatio()
          + setComplexityReductionThreshold()
          + setDetectShadows()
          + setHistory()
          + setNMixtures()
          + setShadowThreshold()
          + setShadowValue()
          + setVarInit()
          + setVarMax()
          + setVarMin()
          + setVarThreshold()
          + setVarThresholdGen()
          # finalize()
          {static} - getDetectShadows_0()
          {static} - getBackgroundRatio_0()
          {static} - getComplexityReductionThreshold_0()
          {static} - getShadowThreshold_0()
          {static} - getVarInit_0()
          {static} - getVarMax_0()
          {static} - getVarMin_0()
          {static} - getVarThreshold_0()
          {static} - getVarThresholdGen_0()
          {static} - getHistory_0()
          {static} - getNMixtures_0()
          {static} - getShadowValue_0()
          {static} - apply_0()
          {static} - apply_1()
          {static} - setBackgroundRatio_0()
          {static} - setComplexityReductionThreshold_0()
          {static} - setDetectShadows_0()
          {static} - setHistory_0()
          {static} - setNMixtures_0()
          {static} - setShadowThreshold_0()
          {static} - setShadowValue_0()
          {static} - setVarInit_0()
          {static} - setVarMax_0()
          {static} - setVarMin_0()
          {static} - setVarThreshold_0()
          {static} - setVarThresholdGen_0()
          {static} - delete()
      }
    }
  }
  

  package org.opencv {
    package org.opencv.video {
      class DenseOpticalFlow {
          # DenseOpticalFlow()
          {static} + __fromPtr__()
          + calc()
          + collectGarbage()
          # finalize()
          {static} - calc_0()
          {static} - collectGarbage_0()
          {static} - delete()
      }
    }
  }
  

  package org.opencv {
    package org.opencv.video {
      class DualTVL1OpticalFlow {
          # DualTVL1OpticalFlow()
          {static} + __fromPtr__()
          {static} + create()
          {static} + create()
          {static} + create()
          {static} + create()
          {static} + create()
          {static} + create()
          {static} + create()
          {static} + create()
          {static} + create()
          {static} + create()
          {static} + create()
          {static} + create()
          {static} + create()
          + getUseInitialFlow()
          + getEpsilon()
          + getGamma()
          + getLambda()
          + getScaleStep()
          + getTau()
          + getTheta()
          + getInnerIterations()
          + getMedianFiltering()
          + getOuterIterations()
          + getScalesNumber()
          + getWarpingsNumber()
          + setEpsilon()
          + setGamma()
          + setInnerIterations()
          + setLambda()
          + setMedianFiltering()
          + setOuterIterations()
          + setScaleStep()
          + setScalesNumber()
          + setTau()
          + setTheta()
          + setUseInitialFlow()
          + setWarpingsNumber()
          # finalize()
          {static} - create_0()
          {static} - create_1()
          {static} - create_2()
          {static} - create_3()
          {static} - create_4()
          {static} - create_5()
          {static} - create_6()
          {static} - create_7()
          {static} - create_8()
          {static} - create_9()
          {static} - create_10()
          {static} - create_11()
          {static} - create_12()
          {static} - getUseInitialFlow_0()
          {static} - getEpsilon_0()
          {static} - getGamma_0()
          {static} - getLambda_0()
          {static} - getScaleStep_0()
          {static} - getTau_0()
          {static} - getTheta_0()
          {static} - getInnerIterations_0()
          {static} - getMedianFiltering_0()
          {static} - getOuterIterations_0()
          {static} - getScalesNumber_0()
          {static} - getWarpingsNumber_0()
          {static} - setEpsilon_0()
          {static} - setGamma_0()
          {static} - setInnerIterations_0()
          {static} - setLambda_0()
          {static} - setMedianFiltering_0()
          {static} - setOuterIterations_0()
          {static} - setScaleStep_0()
          {static} - setScalesNumber_0()
          {static} - setTau_0()
          {static} - setTheta_0()
          {static} - setUseInitialFlow_0()
          {static} - setWarpingsNumber_0()
          {static} - delete()
      }
    }
  }
  

  package org.opencv {
    package org.opencv.video {
      class FarnebackOpticalFlow {
          # FarnebackOpticalFlow()
          {static} + __fromPtr__()
          {static} + create()
          {static} + create()
          {static} + create()
          {static} + create()
          {static} + create()
          {static} + create()
          {static} + create()
          {static} + create()
          {static} + create()
          + getFastPyramids()
          + getPolySigma()
          + getPyrScale()
          + getFlags()
          + getNumIters()
          + getNumLevels()
          + getPolyN()
          + getWinSize()
          + setFastPyramids()
          + setFlags()
          + setNumIters()
          + setNumLevels()
          + setPolyN()
          + setPolySigma()
          + setPyrScale()
          + setWinSize()
          # finalize()
          {static} - create_0()
          {static} - create_1()
          {static} - create_2()
          {static} - create_3()
          {static} - create_4()
          {static} - create_5()
          {static} - create_6()
          {static} - create_7()
          {static} - create_8()
          {static} - getFastPyramids_0()
          {static} - getPolySigma_0()
          {static} - getPyrScale_0()
          {static} - getFlags_0()
          {static} - getNumIters_0()
          {static} - getNumLevels_0()
          {static} - getPolyN_0()
          {static} - getWinSize_0()
          {static} - setFastPyramids_0()
          {static} - setFlags_0()
          {static} - setNumIters_0()
          {static} - setNumLevels_0()
          {static} - setPolyN_0()
          {static} - setPolySigma_0()
          {static} - setPyrScale_0()
          {static} - setWinSize_0()
          {static} - delete()
      }
    }
  }
  

  package org.opencv {
    package org.opencv.video {
      class KalmanFilter {
          # nativeObj : long
          # KalmanFilter()
          + getNativeObjAddr()
          {static} + __fromPtr__()
          + KalmanFilter()
          + KalmanFilter()
          + KalmanFilter()
          + KalmanFilter()
          + correct()
          + predict()
          + predict()
          + get_statePre()
          + set_statePre()
          + get_statePost()
          + set_statePost()
          + get_transitionMatrix()
          + set_transitionMatrix()
          + get_controlMatrix()
          + set_controlMatrix()
          + get_measurementMatrix()
          + set_measurementMatrix()
          + get_processNoiseCov()
          + set_processNoiseCov()
          + get_measurementNoiseCov()
          + set_measurementNoiseCov()
          + get_errorCovPre()
          + set_errorCovPre()
          + get_gain()
          + set_gain()
          + get_errorCovPost()
          + set_errorCovPost()
          # finalize()
          {static} - KalmanFilter_0()
          {static} - KalmanFilter_1()
          {static} - KalmanFilter_2()
          {static} - KalmanFilter_3()
          {static} - correct_0()
          {static} - predict_0()
          {static} - predict_1()
          {static} - get_statePre_0()
          {static} - set_statePre_0()
          {static} - get_statePost_0()
          {static} - set_statePost_0()
          {static} - get_transitionMatrix_0()
          {static} - set_transitionMatrix_0()
          {static} - get_controlMatrix_0()
          {static} - set_controlMatrix_0()
          {static} - get_measurementMatrix_0()
          {static} - set_measurementMatrix_0()
          {static} - get_processNoiseCov_0()
          {static} - set_processNoiseCov_0()
          {static} - get_measurementNoiseCov_0()
          {static} - set_measurementNoiseCov_0()
          {static} - get_errorCovPre_0()
          {static} - set_errorCovPre_0()
          {static} - get_gain_0()
          {static} - set_gain_0()
          {static} - get_errorCovPost_0()
          {static} - set_errorCovPost_0()
          {static} - delete()
      }
    }
  }
  

  package org.opencv {
    package org.opencv.video {
      class SparseOpticalFlow {
          # SparseOpticalFlow()
          {static} + __fromPtr__()
          + calc()
          + calc()
          # finalize()
          {static} - calc_0()
          {static} - calc_1()
          {static} - delete()
      }
    }
  }
  

  package org.opencv {
    package org.opencv.video {
      class SparsePyrLKOpticalFlow {
          # SparsePyrLKOpticalFlow()
          {static} + __fromPtr__()
          {static} + create()
          {static} + create()
          {static} + create()
          {static} + create()
          {static} + create()
          {static} + create()
          + getWinSize()
          + getTermCriteria()
          + getMinEigThreshold()
          + getFlags()
          + getMaxLevel()
          + setFlags()
          + setMaxLevel()
          + setMinEigThreshold()
          + setTermCriteria()
          + setWinSize()
          # finalize()
          {static} - create_0()
          {static} - create_1()
          {static} - create_2()
          {static} - create_3()
          {static} - create_4()
          {static} - create_5()
          {static} - getWinSize_0()
          {static} - getTermCriteria_0()
          {static} - getMinEigThreshold_0()
          {static} - getFlags_0()
          {static} - getMaxLevel_0()
          {static} - setFlags_0()
          {static} - setMaxLevel_0()
          {static} - setMinEigThreshold_0()
          {static} - setTermCriteria_0()
          {static} - setWinSize_0()
          {static} - delete()
      }
    }
  }
  

  package org.opencv {
    package org.opencv.video {
      class Video {
          {static} - CV_LKFLOW_INITIAL_GUESSES : int
          {static} - CV_LKFLOW_GET_MIN_EIGENVALS : int
          {static} + OPTFLOW_USE_INITIAL_FLOW : int
          {static} + OPTFLOW_LK_GET_MIN_EIGENVALS : int
          {static} + OPTFLOW_FARNEBACK_GAUSSIAN : int
          {static} + MOTION_TRANSLATION : int
          {static} + MOTION_EUCLIDEAN : int
          {static} + MOTION_AFFINE : int
          {static} + MOTION_HOMOGRAPHY : int
          {static} + estimateRigidTransform()
          {static} + estimateRigidTransform()
          {static} + createBackgroundSubtractorKNN()
          {static} + createBackgroundSubtractorKNN()
          {static} + createBackgroundSubtractorKNN()
          {static} + createBackgroundSubtractorKNN()
          {static} + createBackgroundSubtractorMOG2()
          {static} + createBackgroundSubtractorMOG2()
          {static} + createBackgroundSubtractorMOG2()
          {static} + createBackgroundSubtractorMOG2()
          {static} + createOptFlow_DualTVL1()
          {static} + CamShift()
          {static} + findTransformECC()
          {static} + findTransformECC()
          {static} + findTransformECC()
          {static} + findTransformECC()
          {static} + buildOpticalFlowPyramid()
          {static} + buildOpticalFlowPyramid()
          {static} + buildOpticalFlowPyramid()
          {static} + buildOpticalFlowPyramid()
          {static} + buildOpticalFlowPyramid()
          {static} + meanShift()
          {static} + calcOpticalFlowFarneback()
          {static} + calcOpticalFlowPyrLK()
          {static} + calcOpticalFlowPyrLK()
          {static} + calcOpticalFlowPyrLK()
          {static} + calcOpticalFlowPyrLK()
          {static} + calcOpticalFlowPyrLK()
          {static} + calcOpticalFlowPyrLK()
          {static} - estimateRigidTransform_0()
          {static} - estimateRigidTransform_1()
          {static} - createBackgroundSubtractorKNN_0()
          {static} - createBackgroundSubtractorKNN_1()
          {static} - createBackgroundSubtractorKNN_2()
          {static} - createBackgroundSubtractorKNN_3()
          {static} - createBackgroundSubtractorMOG2_0()
          {static} - createBackgroundSubtractorMOG2_1()
          {static} - createBackgroundSubtractorMOG2_2()
          {static} - createBackgroundSubtractorMOG2_3()
          {static} - createOptFlow_DualTVL1_0()
          {static} - CamShift_0()
          {static} - findTransformECC_0()
          {static} - findTransformECC_1()
          {static} - findTransformECC_2()
          {static} - findTransformECC_3()
          {static} - buildOpticalFlowPyramid_0()
          {static} - buildOpticalFlowPyramid_1()
          {static} - buildOpticalFlowPyramid_2()
          {static} - buildOpticalFlowPyramid_3()
          {static} - buildOpticalFlowPyramid_4()
          {static} - meanShift_0()
          {static} - calcOpticalFlowFarneback_0()
          {static} - calcOpticalFlowPyrLK_0()
          {static} - calcOpticalFlowPyrLK_1()
          {static} - calcOpticalFlowPyrLK_2()
          {static} - calcOpticalFlowPyrLK_3()
          {static} - calcOpticalFlowPyrLK_4()
          {static} - calcOpticalFlowPyrLK_5()
      }
    }
  }
  

  BackgroundSubtractor -up-|> Algorithm
  BackgroundSubtractorKNN -up-|> BackgroundSubtractor
  BackgroundSubtractorMOG2 -up-|> BackgroundSubtractor
  DenseOpticalFlow -up-|> Algorithm
  DualTVL1OpticalFlow -up-|> DenseOpticalFlow
  FarnebackOpticalFlow -up-|> DenseOpticalFlow
  SparseOpticalFlow -up-|> Algorithm
  SparsePyrLKOpticalFlow -up-|> SparseOpticalFlow


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
